baseURL = "https://foam.med.schu.im"
languageCode = "de"
title = "foam.med.schu.im"

theme = "about-blank"

enableGitInfo = true

[params]
author = "Michael Schubert"
disableMenu = true

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4
